openapi: 3.0.0
info:
  title: Groundhog Day API
  version: 1.1.1
  description: This API returns all of North America's prognosticating animals and their yearly weather predictions.
  contact:
    name: Paul Craig
    url: 'https://groundhog-day.com/api'
    email: hello@groundhog-day.com
  license:
    name: MIT
servers:
  - url: 'https://groundhog-day.com'
    description: ''
components:
  schemas:
    Groundhog:
      type: object
      x-examples:
        /groundhog/lucy-the-lobster:
          id: 46
          slug: lucy-the-lobster
          shortname: Lucy
          name: Lucy the Lobster
          city: Barrington
          region: Nova Scotia
          country: Canada
          source: 'https://twitter.com/lucylobsterns'
          contact: ''
          currentPrediction: 'https://twitter.com/CailinONeil/status/1488894511107485702'
          isGroundhog: 0
          type: Atlantic lobster
          active: 1
          description: 'Lucy the Lobster makes Groundhog Day predictions on February 2nd to kick off the Lobster Crawl festival in Barrington, Nova Scotia. The Municipality of Barrington says Lucy is the only prognosticating crustacean to make a prediction in Canada. Bill Murray was reported as being bemused by the idea of a lobster forecaster.'
          image: 'https://groundhog-day.com/images/ghogs/lucy-the-lobster.png'
          predictions:
            - year: 2018
              shadow: 0
              details: ''
            - year: 2019
              shadow: 1
              details: ''
            - year: 2020
              shadow: 1
              details: ''
            - year: 2021
              shadow: null
              details: ''
            - year: 2022
              shadow: 1
              details: ''
      description: An animal that makes an annual prediction on Groundhog Day.
      title: Groundhog
      properties:
        id:
          type: integer
          minimum: 1
        slug:
          type: string
        shortname:
          type: string
        name:
          type: string
        city:
          type: string
        region:
          type: string
        country:
          type: string
        source:
          type: string
        contact:
          type: string
        currentPrediction:
          type: string
        isGroundhog:
          type: integer
          minimum: 0
          maximum: 1
          exclusiveMinimum: false
          exclusiveMaximum: false
          format: binary
        type:
          type: string
        active:
          type: integer
          format: binary
          minimum: 0
          maximum: 1
          exclusiveMinimum: false
          exclusiveMaximum: false
          enum:
            - 0
            - 1
        description:
          type: string
        image:
          type: string
        predictions:
          type: array
          items:
            $ref: '#/components/schemas/Prediction'
      required:
        - id
        - slug
        - shortname
        - name
        - city
        - region
        - country
        - source
        - contact
        - currentPrediction
        - isGroundhog
        - type
        - active
        - description
        - image
    Prediction:
      type: object
      x-examples:
        /predictions?year=2022:
          year: 2022
          shadow: 1
          details: ''
          groundhog:
            id: 46
            slug: lucy-the-lobster
            shortname: Lucy
            name: Lucy the Lobster
            city: Barrington
            region: Nova Scotia
            country: Canada
            source: 'https://twitter.com/lucylobsterns'
            contact: ''
            currentPrediction: 'https://twitter.com/CailinONeil/status/1488894511107485702'
            isGroundhog: 0
            type: Atlantic lobster
            active: 1
            description: 'Lucy the Lobster makes Groundhog Day predictions on February 2nd to kick off the Lobster Crawl festival in Barrington, Nova Scotia. The Municipality of Barrington says Lucy is the only prognosticating crustacean to make a prediction in Canada. Bill Murray was reported as being bemused by the idea of a lobster forecaster.'
            image: 'https://groundhog-day.com/images/ghogs/lucy-the-lobster.png'
      title: Prediction
      description: An annual prediction of an early spring or a longer winter.
      properties:
        year:
          type: integer
          minimum: 1886
          exclusiveMinimum: false
        shadow:
          type: integer
          minimum: 0
          maximum: 1
          nullable: true
        details:
          type: string
        groundhog:
          $ref: '#/components/schemas/Groundhog'
      required:
        - year
paths:
  /api/v1:
    get:
      summary: Root
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    message: 'Hello! Welcome to the Groundhog Day API: the leading Groundhog Day data source'
                    _links:
                      self:
                        href: 'https://groundhog-day.com/api/v1/'
                      groundhogs:
                        href: 'https://groundhog-day.com/api/v1/groundhogs'
                      groundhog:
                        href: 'https://groundhog-day.com/api/v1/groundhogs/wiarton-willie'
                      predictions:
                        href: 'https://groundhog-day.com/api/v1/predictions?year=2022'
                      spec:
                        href: 'https://groundhog-day.com/api/v1/spec'
                properties:
                  message:
                    type: string
                  _links:
                    type: object
                    properties:
                      self:
                        type: object
                        required:
                          - href
                        properties:
                          href:
                            type: string
                      groundhogs:
                        type: object
                        properties:
                          href:
                            type: string
                        required:
                          - href
                      groundhog:
                        type: object
                        properties:
                          href:
                            type: string
                        required:
                          - href
                      predictions:
                        type: object
                        properties:
                          href:
                            type: string
                        required:
                          - href
                      spec:
                        type: object
                        properties:
                          href:
                            type: string
                        required:
                          - href
                required:
                  - message
              examples:
                /:
                  value:
                    message: 'Hello! Welcome to the Groundhog Day API: the leading Groundhog Day data source'
                    _links:
                      self:
                        href: 'https://groundhog-day.com/api/v1/'
                      groundhogs:
                        href: 'https://groundhog-day.com/api/v1/groundhogs'
                      groundhog:
                        href: 'https://groundhog-day.com/api/v1/groundhogs/wiarton-willie'
                      predictions:
                        href: 'https://groundhog-day.com/api/v1/predictions?year=2022'
                      spec:
                        href: 'https://groundhog-day.com/api/v1/spec'
      operationId: root
      description: Returns a welcome message.
      tags:
        - info
  /api/v1/groundhogs:
    get:
      summary: Get all groundhogs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    - id: 1
                      slug: punxsutawney-phil
                      shortname: Phil
                      name: Punxsutawney Phil
                      city: Punxsutawney
                      region: Pennsylvania
                      country: USA
                      source: 'https://www.groundhog.org/history-past-predictions'
                      contact: ''
                      currentPrediction: 'https://www.groundhog.org/prognostication'
                      isGroundhog: 1
                      type: Groundhog
                      active: 1
                      description: 'Punxsutawney Phil is a superstar prognosticating groundhog from Punxsutawney, Pennsylvania. He makes his predictions from his burrow on Gobler’s Knob. According to legend, Phil has made weather prognostications since 1886, owing his improbably long life to the miraculous “groundhog nog” administered at the annual Groundhog Picnic.'
                      image: 'https://groundhog-day.com/images/ghogs/punxsutawney-phil.png'
                      predictionsCount: 7
                      predictions:
                        - year: 2016
                          shadow: 0
                          details: 'No Shadow- Early Spring It was 28° at Gobbler’s Knob. Phil made his perdition of an Early Spring at 7:25 a.m.'
                        - year: 2017
                          shadow: 1
                          details: '7:25 a.m. Saw His Shadow, Six More Weeks of Winter! There were a few snow flurries during the prognostication.'
                        - year: 2018
                          shadow: 1
                          details: 'At 7:25 a.m. with 18,000 Phil Phans present, Phil saw his shadow! Six More Weeks of Winter!'
                        - year: 2019
                          shadow: 0
                          details: 'NO Shadow at 7:28 AM; 14º fog & mist with -1º Wind Chill.'
                        - year: 2020
                          shadow: 0
                          details: 'NO Shadow at 7:26 AM; 30º with light snow falling.'
                        - year: 2021
                          shadow: 1
                          details: 'Shadow at 7:25 AM; 19º with light snow. Coronavirus fear prohibits crowds on Gobbler’s Knob.'
                        - year: 2022
                          shadow: 1
                          details: 'Shadow at 7:27 AM; 27º with clear skies. A loyal crowd of thousands returned to Gobbler’s Knob.'
                    - id: 46
                      slug: lucy-the-lobster
                      shortname: Lucy
                      name: Lucy the Lobster
                      city: Barrington
                      region: Nova Scotia
                      country: Canada
                      source: 'https://twitter.com/lucylobsterns'
                      contact: ''
                      currentPrediction: 'https://twitter.com/CailinONeil/status/1488894511107485702'
                      isGroundhog: 0
                      type: Atlantic lobster
                      active: 1
                      description: 'Lucy the Lobster makes Groundhog Day predictions on February 2nd to kick off the Lobster Crawl festival in Barrington, Nova Scotia. The Municipality of Barrington says Lucy is the only prognosticating crustacean to make a prediction in Canada. Bill Murray was reported as being bemused by the idea of a lobster forecaster.'
                      image: 'https://groundhog-day.com/images/ghogs/lucy-the-lobster.png'
                      predictionsCount: 4
                      predictions:
                        - year: 2018
                          shadow: 0
                          details: ''
                        - year: 2019
                          shadow: 1
                          details: ''
                        - year: 2020
                          shadow: 1
                          details: ''
                        - year: 2021
                          shadow: null
                          details: ''
                        - year: 2022
                          shadow: 1
                          details: ''
                properties:
                  groundhogs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Groundhog'
              examples:
                /groundhogs:
                  value:
                    groundhogs:
                      - id: 1
                        slug: punxsutawney-phil
                        shortname: Phil
                        name: Punxsutawney Phil
                        city: Punxsutawney
                        region: Pennsylvania
                        country: USA
                        source: 'https://www.groundhog.org/history-past-predictions'
                        contact: ''
                        currentPrediction: 'https://www.groundhog.org/prognostication'
                        isGroundhog: 1
                        type: Groundhog
                        active: 1
                        description: 'Punxsutawney Phil is a superstar prognosticating groundhog from Punxsutawney, Pennsylvania. He makes his predictions from his burrow on Gobler’s Knob. According to legend, Phil has made weather prognostications since 1886, owing his improbably long life to the miraculous “groundhog nog” administered at the annual Groundhog Picnic.'
                        image: 'https://groundhog-day.com/images/ghogs/punxsutawney-phil.png'
                        predictionsCount: 7
                        predictions:
                          - year: 2016
                            shadow: 0
                            details: 'No Shadow- Early Spring It was 28° at Gobbler’s Knob. Phil made his perdition of an Early Spring at 7:25 a.m.'
                          - year: 2017
                            shadow: 1
                            details: '7:25 a.m. Saw His Shadow, Six More Weeks of Winter! There were a few snow flurries during the prognostication.'
                          - year: 2018
                            shadow: 1
                            details: 'At 7:25 a.m. with 18,000 Phil Phans present, Phil saw his shadow! Six More Weeks of Winter!'
                          - year: 2019
                            shadow: 0
                            details: 'NO Shadow at 7:28 AM; 14º fog & mist with -1º Wind Chill.'
                          - year: 2020
                            shadow: 0
                            details: 'NO Shadow at 7:26 AM; 30º with light snow falling.'
                          - year: 2021
                            shadow: 1
                            details: 'Shadow at 7:25 AM; 19º with light snow. Coronavirus fear prohibits crowds on Gobbler’s Knob.'
                          - year: 2022
                            shadow: 1
                            details: 'Shadow at 7:27 AM; 27º with clear skies. A loyal crowd of thousands returned to Gobbler’s Knob.'
                      - id: 46
                        slug: lucy-the-lobster
                        shortname: Lucy
                        name: Lucy the Lobster
                        city: Barrington
                        region: Nova Scotia
                        country: Canada
                        source: 'https://twitter.com/lucylobsterns'
                        contact: ''
                        currentPrediction: 'https://twitter.com/CailinONeil/status/1488894511107485702'
                        isGroundhog: 0
                        type: Atlantic lobster
                        active: 1
                        description: 'Lucy the Lobster makes Groundhog Day predictions on February 2nd to kick off the Lobster Crawl festival in Barrington, Nova Scotia. The Municipality of Barrington says Lucy is the only prognosticating crustacean to make a prediction in Canada. Bill Murray was reported as being bemused by the idea of a lobster forecaster.'
                        image: 'https://groundhog-day.com/images/ghogs/lucy-the-lobster.png'
                        predictionsCount: 4
                        predictions:
                          - year: 2018
                            shadow: 0
                            details: ''
                          - year: 2019
                            shadow: 1
                            details: ''
                          - year: 2020
                            shadow: 1
                            details: ''
                          - year: 2021
                            shadow: null
                            details: ''
                          - year: 2022
                            shadow: 1
                            details: ''
      operationId: groundhogs
      description: Returns all prognosticating animals with their known predictions.
      tags:
        - groundhogs
      parameters:
        - schema:
            type: string
            example: Canada or USA
          in: query
          name: country
          description: Filter groundhogs by country of origin (USA or Canada).
  '/api/v1/groundhogs/{slug}':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: 'Groundhog name in kebab-case: (eg, lucy-the-lobster)'
    get:
      summary: Get a groundhog by slug
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  groundhog:
                    $ref: '#/components/schemas/Groundhog'
              examples:
                /groundhogs/lucy-the-lobster:
                  value:
                    groundhog:
                      id: 46
                      slug: lucy-the-lobster
                      shortname: Lucy
                      name: Lucy the Lobster
                      city: Barrington
                      region: Nova Scotia
                      country: Canada
                      source: 'https://twitter.com/lucylobsterns'
                      contact: ''
                      currentPrediction: 'https://twitter.com/CailinONeil/status/1488894511107485702'
                      isGroundhog: 0
                      type: Atlantic lobster
                      active: 1
                      description: 'Lucy the Lobster makes Groundhog Day predictions on February 2nd to kick off the Lobster Crawl festival in Barrington, Nova Scotia. The Municipality of Barrington says Lucy is the only prognosticating crustacean to make a prediction in Canada. Bill Murray was reported as being bemused by the idea of a lobster forecaster.'
                      image: 'https://groundhog-day.com/images/ghogs/lucy-the-lobster.png'
                      predictions:
                        - year: 2018
                          shadow: 0
                          details: ''
                        - year: 2019
                          shadow: 1
                          details: ''
                        - year: 2020
                          shadow: 1
                          details: ''
                        - year: 2021
                          shadow: null
                          details: ''
                        - year: 2022
                          shadow: 1
                          details: ''
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    error:
                      status: 400
                      message: 'BadRequestError: Bad groundhog identifier (''fake''), maybe you spelled it wrong?'
                      timestamp: '2022-10-03T03:36:54.661Z'
                properties:
                  error:
                    type: object
                    properties:
                      status:
                        type: integer
                      message:
                        type: string
                      timestamp:
                        type: string
                    required:
                      - status
                      - message
                      - timestamp
              examples:
                /groundhogs/punxsutawney-paul:
                  value:
                    error:
                      status: 400
                      message: 'BadRequestError: Bad groundhog identifier (''punxsutawney-paul''), maybe you spelled it wrong?'
                      timestamp: '2022-10-03T03:37:51.567Z'
      operationId: groundhog
      description: Returns a prognosticating animal and its known predictions.
      tags:
        - groundhogs
  /api/v1/predictions:
    parameters: []
    get:
      summary: Get predictions for a given year
      tags:
        - predictions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    - year: 2020
                      shadow: 0
                      details: 'NO Shadow at 7:26 AM; 30º with light snow falling.'
                      groundhog:
                        id: 1
                        slug: punxsutawney-phil
                        shortname: Phil
                        name: Punxsutawney Phil
                        city: Punxsutawney
                        region: Pennsylvania
                        country: USA
                        source: 'https://www.groundhog.org/history-past-predictions'
                        contact: ''
                        currentPrediction: 'https://www.groundhog.org/prognostication'
                        isGroundhog: 1
                        type: Groundhog
                        active: 1
                        description: 'Punxsutawney Phil is a superstar prognosticating groundhog from Punxsutawney, Pennsylvania. He makes his predictions from his burrow on Gobler’s Knob. According to legend, Phil has made weather prognostications since 1886, owing his improbably long life to the miraculous “groundhog nog” administered at the annual Groundhog Picnic.'
                        image: 'https://groundhog-day.com/images/ghogs/punxsutawney-phil.png'
                    - year: 2020
                      shadow: 1
                      details: ''
                      groundhog:
                        id: 46
                        slug: lucy-the-lobster
                        shortname: Lucy
                        name: Lucy the Lobster
                        city: Barrington
                        region: Nova Scotia
                        country: Canada
                        source: 'https://twitter.com/lucylobsterns'
                        contact: ''
                        currentPrediction: 'https://twitter.com/CailinONeil/status/1488894511107485702'
                        isGroundhog: 0
                        type: Atlantic lobster
                        active: 1
                        description: 'Lucy the Lobster makes Groundhog Day predictions on February 2nd to kick off the Lobster Crawl festival in Barrington, Nova Scotia. The Municipality of Barrington says Lucy is the only prognosticating crustacean to make a prediction in Canada. Bill Murray was reported as being bemused by the idea of a lobster forecaster.'
                        image: 'https://groundhog-day.com/images/ghogs/lucy-the-lobster.png'
                properties:
                  predictions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Prediction'
              examples:
                /predictions?year=2020:
                  value:
                    predictions:
                      - year: 2020
                        shadow: 0
                        details: 'NO Shadow at 7:26 AM; 30º with light snow falling.'
                        groundhog:
                          id: 1
                          slug: punxsutawney-phil
                          shortname: Phil
                          name: Punxsutawney Phil
                          city: Punxsutawney
                          region: Pennsylvania
                          country: USA
                          source: 'https://www.groundhog.org/history-past-predictions'
                          contact: ''
                          currentPrediction: 'https://www.groundhog.org/prognostication'
                          isGroundhog: 1
                          type: Groundhog
                          active: 1
                          description: 'Punxsutawney Phil is a superstar prognosticating groundhog from Punxsutawney, Pennsylvania. He makes his predictions from his burrow on Gobler’s Knob. According to legend, Phil has made weather prognostications since 1886, owing his improbably long life to the miraculous “groundhog nog” administered at the annual Groundhog Picnic.'
                          image: 'https://groundhog-day.com/images/ghogs/punxsutawney-phil.png'
                      - year: 2020
                        shadow: 1
                        details: ''
                        groundhog:
                          id: 46
                          slug: lucy-the-lobster
                          shortname: Lucy
                          name: Lucy the Lobster
                          city: Barrington
                          region: Nova Scotia
                          country: Canada
                          source: 'https://twitter.com/lucylobsterns'
                          contact: ''
                          currentPrediction: 'https://twitter.com/CailinONeil/status/1488894511107485702'
                          isGroundhog: 0
                          type: Atlantic lobster
                          active: 1
                          description: 'Lucy the Lobster makes Groundhog Day predictions on February 2nd to kick off the Lobster Crawl festival in Barrington, Nova Scotia. The Municipality of Barrington says Lucy is the only prognosticating crustacean to make a prediction in Canada. Bill Murray was reported as being bemused by the idea of a lobster forecaster.'
                          image: 'https://groundhog-day.com/images/ghogs/lucy-the-lobster.png'
        '302':
          description: Found
          headers:
            location:
              schema:
                type: string
              description: /api/v1/predictions?year=2022
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    error:
                      status: 400
                      message: 'BadRequestError: The ''year'' must be between 1886 and 2022 (inclusive).'
                      timestamp: '2022-10-03T03:38:55.169Z'
                properties:
                  error:
                    type: object
                    properties:
                      status:
                        type: integer
                      message:
                        type: string
                      timestamp:
                        type: string
                    required:
                      - status
                      - message
                      - timestamp
              examples:
                /predictions?year=1800:
                  value:
                    error:
                      status: 400
                      message: 'BadRequestError: The ''year'' must be between 1886 and 2022 (inclusive).'
                      timestamp: '2022-10-03T03:38:55.169Z'
      operationId: predictions
      description: Get all predictions for a given year.
      parameters:
        - schema:
            type: integer
            minimum: 1886
          in: query
          name: year
          description: A calendar year
  /api/v1/spec:
    get:
      summary: Get JSON schema
      responses:
        '200':
          description: OK
          headers:
            content-disposition:
              schema:
                type: string
              description: attachment; filename="Groundhog-Day-API.v1.yaml"
            content-type:
              schema:
                type: string
              description: text/yaml; charset=UTF-8
      operationId: spec
      description: Gets the schema for the JSON API as a yaml file.
      tags:
        - info
tags:
  - name: info
  - name: groundhogs
  - name: predictions
